site_name: Semantic Kernel Graph
site_description: Documentation for SemanticKernel.Graph, inspired by LangGraph, built with Material for MkDocs
docs_dir: docs

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - content.action.edit
    - toc.follow
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/microsoft/semantic-kernel
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started.md
      - Installation: installation.md
      - First Graph: first-graph.md
      - Quickstarts:
          - First Graph in 5 Minutes: first-graph-5-minutes.md
          - State Management: state-quickstart.md
          - Conditional Nodes: conditional-nodes-quickstart.md
          - Checkpointing: checkpointing-quickstart.md
          - Streaming: streaming-quickstart.md
          - Metrics & Logging: metrics-logging-quickstart.md
          - ReAct & Chain of Thought: react-cot-quickstart.md
      - Tutorials:
          - State Management: state-tutorial.md
          - Conditional Nodes: conditional-nodes-tutorial.md
  - Concepts:
      - Overview: concepts/index.md
      - Graph Concepts: concepts/graph-concepts.md
      - Graphs: concepts/graphs.md
      - Nodes: concepts/nodes.md
      - Node Types: concepts/node-types.md
      - State: concepts/state.md
      - Edges & Routing: concepts/routing.md
      - Execution: concepts/execution.md
      - Execution Model: concepts/execution-model.md
      - Checkpointing: concepts/checkpointing.md
      - Streaming: concepts/streaming.md
      - Visualization: concepts/visualization.md
  - How-to guides:
      - Core:
          - Build a graph: how-to/build-a-graph.md
          - Conditional nodes: how-to/conditional-nodes.md
          - Loops: how-to/loops.md
      - Advanced:
          - Advanced routing: how-to/advanced-routing.md
          - Parallelism: how-to/parallelism-and-fork-join.md
          - Error handling: how-to/error-handling-and-resilience.md
      - Integration:
          - Tools: how-to/tools.md
          - REST tools: how-to/rest-tools-integration.md
          - Multi-agent: how-to/multi-agent-and-shared-state.md
          - Integration & Extensions: how-to/integration-and-extensions.md
      - Observability:
          - Metrics: how-to/metrics-and-observability.md
          - Debug: how-to/debug-and-inspection.md
          - Visualization: how-to/real-time-visualization-and-highlights.md
      - Security & Governance:
          - Security: how-to/security-and-data.md
          - Resource governance: how-to/resource-governance-and-concurrency.md
          - Human-in-the-loop: how-to/human-in-the-loop.md
      - Server & APIs:
          - Server and APIs: how-to/server-and-apis.md
          - Exposing REST APIs: how-to/exposing-rest-apis.md
      - Templates & Memory:
          - Templates and Memory: how-to/templates-and-memory.md
          - Schema Typing and Validation: how-to/schema-typing-and-validation.md
  - Patterns:
      - ReAct: patterns/react.md
      - Chain-of-Thought: patterns/chain-of-thought.md
      - Multi-agent: patterns/multi-agent.md
  - Examples:
      - Overview: examples/index.md
      - Core Patterns:
          - Conditional Nodes: examples/conditional-nodes.md
          - Loops: examples/loop-nodes.md
          - State Management: examples/checkpointing.md
      - AI Patterns:
          - Chain of Thought: examples/chain-of-thought.md
          - ReAct: examples/react-agent.md
          - Multi-agent: examples/multi-agent.md
      - Advanced Features:
          - Advanced Patterns: examples/advanced-patterns.md
          - Advanced Routing: examples/advanced-routing.md
          - Dynamic Routing: examples/dynamic-routing.md
      - Integration:
          - REST API: examples/rest-api.md
          - Plugin System: examples/plugin-system.md
          - Tools: examples/tools.md
      - Observability:
          - Metrics: examples/graph-metrics.md
          - Visualization: examples/graph-visualization.md
          - Logging: examples/logging.md
      - Workflows:
          - Chatbot: examples/chatbot.md
          - Document Analysis: examples/document-analysis-pipeline.md
          - Retrieval Agent: examples/retrieval-agent.md
      - Specialized:
          - Memory Agent: examples/memory-agent.md
          - Multi-hop RAG Retry: examples/multi-hop-rag-retry.md
          - Optimizers and Few-shot: examples/optimizers-and-few-shot.md
          - Assert and Suggest: examples/assert-and-suggest.md
          - Subgraphs: examples/subgraph-examples.md
          - Streaming Execution: examples/streaming-execution.md
      - Templates:
          - Analysis Standard Sections: examples/analysis-standard-sections.md
          - Template Standard Sections: examples/template-standard-sections.md
          - Execution Guide: examples/execution-guide.md
  - API reference:
      - Core: api/core.md
      - Nodes: api/nodes.md
      - Extensions: api/extensions.md
      - Integration: api/integration.md
      - Error Policies: api/error-policies.md
      - Multi-Agent: api/multi-agent.md
      - Validation & Compilation: api/validation-compilation.md
      - Visualization & Realtime: api/visualization-realtime.md
      - Server & APIs: api/server-apis.md
      - Graph Options: api/graph-options.md
      - Additional Utilities: api/additional-utilities.md
      - Conditional Edge: api/conditional-edge.md
      - Dynamic Routing: api/dynamic-routing.md
      - Execution Context: api/execution-context.md
      - Executors & Middlewares: api/executors-and-middlewares.md
      - Graph Executor: api/graph-executor.md
      - Human-in-the-Loop: api/human-in-the-loop.md
      - IGraph Executor: api/igraph-executor.md
      - IGraph Node: api/igraph-node.md
      - Inspection & Visualization: api/inspection-visualization.md
      - Main Node Types: api/main-node-types.md
      - Metrics: api/metrics.md
      - REST Tools: api/rest-tools.md
      - State & Serialization: api/state-and-serialization.md
      - Streaming: api/streaming.md
  - Architecture:
      - Overview: architecture/index.md
      - ADR-0001 GraphExecutor Design: architecture/adr-0001-graph-executor-design.md
      - ADR-0002 Error Recovery Engine: architecture/adr-0002-error-recovery-engine.md
      - ADR-0003 Dynamic Routing: architecture/adr-0003-dynamic-routing.md
      - ADR-0004 Streaming Execution: architecture/adr-0004-streaming-execution.md
      - ADR-0005 State & Checkpointing: architecture/adr-0005-state-and-checkpointing.md
      - ADR-0006 Metrics & Telemetry: architecture/adr-0006-metrics-and-telemetry.md
      - ADR-0007 Multi-Agent Coordination: architecture/adr-0007-multi-agent-coordination.md
      - ADR-0008 Resource Governance: architecture/adr-0008-resource-governance.md
      - ADR-0009 Human-in-the-Loop: architecture/adr-0009-human-in-the-loop.md
      - ADR-0010 Security & Auth: architecture/adr-0010-security-and-auth.md
      - ADR-0011 Tool Registry & REST Tools: architecture/adr-0011-tool-registry-and-rest-tools.md
      - ADR-0012 Visualization & Inspection: architecture/adr-0012-visualization-and-inspection.md
      - ADR-0013 Workflow Templates: architecture/adr-0013-workflow-templates.md
      - ADR-0014 Distributed Execution: architecture/adr-0014-distributed-execution.md
      - ADR-0015 Python Bridge: architecture/adr-0015-python-bridge.md
  - Migrations:
      - From Semantic Kernel: migrations/index.md
  - Tutorials:
      - Overview: tutorials/index.md
      - Chatbot with Memory: tutorials/chatbot-with-memory.md
      - Document Analysis Pipeline: tutorials/document-analysis-pipeline.md
      - Multi-Agent Workflow: tutorials/multi-agent-workflow.md
  - Reference:
      - Glossary: glossary.md
      - Running Examples: running-examples.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md
  - Changelog: changelog.md


