site_name: Semantic Kernel Graph
site_description: Documentation for SemanticKernel.Graph, inspired by LangGraph, built with Material for MkDocs
docs_dir: .

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - content.action.edit
    - toc.follow

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started.md
      - Installation: installation.md
      - First Graph: first-graph.md
      - State Management: state-tutorial.md
      - Conditional Nodes: conditional-nodes-tutorial.md
  - Concepts:
      - Overview: concepts/index.md
      - Graphs: concepts/graphs.md
      - State: concepts/state.md
      - Nodes: concepts/nodes.md
      - Edges & Routing: concepts/routing.md
      - Execution: concepts/execution.md
      - Checkpointing: concepts/checkpointing.md
      - Streaming: concepts/streaming.md
      - Visualization: concepts/visualization.md
  - How-to guides:
      - Build a graph: how-to/build-a-graph.md
      - Conditional nodes: how-to/conditional-nodes.md
      - Loops: how-to/loops.md
      - Human-in-the-loop: how-to/hitl.md
      - Integrate tools: how-to/tools.md
  - Patterns:
      - ReAct: patterns/react.md
      - Chain-of-Thought: patterns/chain-of-thought.md
      - Multi-agent: patterns/multi-agent.md
  - API reference:
      - Core: api/core.md
      - Nodes: api/nodes.md
      - Extensions: api/extensions.md
      - Integration: api/integration.md
      - Error Policies: api/error-policies.md
      - Multi-Agent: api/multi-agent.md
      - Validation & Compilation: api/validation-compilation.md
      - Visualization & Realtime: api/visualization-realtime.md
      - Server & APIs: api/server-apis.md
      - Graph Options: api/graph-options.md
  - Architecture:
      - Overview: architecture/index.md
      - ADR-0001 GraphExecutor Design: architecture/adr-0001-graph-executor-design.md
      - ADR-0002 Error Recovery Engine: architecture/adr-0002-error-recovery-engine.md
      - ADR-0003 Dynamic Routing: architecture/adr-0003-dynamic-routing.md
      - ADR-0004 Streaming Execution: architecture/adr-0004-streaming-execution.md
      - ADR-0005 State & Checkpointing: architecture/adr-0005-state-and-checkpointing.md
      - ADR-0006 Metrics & Telemetry: architecture/adr-0006-metrics-and-telemetry.md
      - ADR-0007 Multi-Agent Coordination: architecture/adr-0007-multi-agent-coordination.md
      - ADR-0008 Resource Governance: architecture/adr-0008-resource-governance.md
      - ADR-0009 Human-in-the-Loop: architecture/adr-0009-human-in-the-loop.md
      - ADR-0010 Security & Auth: architecture/adr-0010-security-and-auth.md
      - ADR-0011 Tool Registry & REST Tools: architecture/adr-0011-tool-registry-and-rest-tools.md
      - ADR-0012 Visualization & Inspection: architecture/adr-0012-visualization-and-inspection.md
      - ADR-0013 Workflow Templates: architecture/adr-0013-workflow-templates.md
      - ADR-0014 Distributed Execution: architecture/adr-0014-distributed-execution.md
      - ADR-0015 Python Bridge: architecture/adr-0015-python-bridge.md
  - Migrations:
      - From Semantic Kernel: migrations/index.md
  - Tutorials:
      - Overview: tutorials/index.md
      - Chatbot with Memory: tutorials/chatbot-with-memory.md
      - Document Analysis Pipeline: tutorials/document-analysis-pipeline.md
      - Multi-Agent Workflow: tutorials/multi-agent-workflow.md
  - Troubleshooting: troubleshooting.md
  - Examples: examples/index.md
  - FAQ: faq.md
  - Changelog: changelog.md

