name: Build and Deploy Documentation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - 'scripts/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - 'scripts/**'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for better link checking
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material pyyaml
    
    - name: Generate llms.txt
      run: |
        cd docs
        python scripts/generate_llms_txt.py --validate-links --check-size --ci
    
    - name: Build documentation
      run: |
        cd docs
        python scripts/build_docs.py --validate --ci --output-dir ../site
    
    - name: Check llms.txt size
      run: |
        cd docs
        llms_size=$(wc -c < llms.txt)
        llms_size_kb=$((llms_size / 1024))
        echo "llms.txt size: ${llms_size_kb} KB"
        if [ $llms_size_kb -gt 50 ]; then
          echo "ERROR: llms.txt exceeds 50 KB limit"
          exit 1
        fi
    
    - name: Validate links
      run: |
        cd docs
        python scripts/generate_llms_txt.py --validate-links --ci
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: documentation-build
        path: site/
        retention-days: 30
    
    - name: Comment PR with build status
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const llmsPath = 'docs/llms.txt';
          
          let comment = '## 📚 Documentation Build Status\n\n';
          comment += '✅ Documentation built successfully\n';
          
          if (fs.existsSync(llmsPath)) {
            const stats = fs.statSync(llmsPath);
            const sizeKB = (stats.size / 1024).toFixed(1);
            comment += `📄 llms.txt generated (${sizeKB} KB)\n`;
            
            if (stats.size > 50 * 1024) {
              comment += '⚠️ **Warning**: llms.txt exceeds recommended size limit\n';
            }
          } else {
            comment += '❌ llms.txt generation failed\n';
          }
          
          comment += '\n---\n';
          comment += 'This comment was automatically generated by the documentation build workflow.';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });

  deploy-docs:
    needs: build-docs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: documentation-build
        path: site/
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'docs: update documentation [skip ci]'
    
    - name: Verify llms.txt deployment
      run: |
        # Check if llms.txt is accessible on GitHub Pages
        sleep 30  # Wait for deployment
        curl -f "https://${{ github.repository_owner }}.github.io/semantic-kernel-graph-pkg/llms.txt" || {
          echo "ERROR: llms.txt not accessible on GitHub Pages"
          exit 1
        }
